#%RAML 0.8
version: v1.0
title: Home IOT Machine

/employee/add:
 post:
  responses: 
   200:
    body:
     application/json:

/employee/update:
 post:
  responses:
   200:
    body:
     application/json:
 
/employee/delete:
 post:
  responses:
   200:
    body:
     application/json:
 
/employee/retrieve:
 get:
  responses:
   200:
    body:
     application/json:
 